// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxNotification struct {
	ID        int64
	OwnerID   int64
	CommentID int64
	Ts        pgtype.Timestamp
	Status    string
}
