// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	GetCommentsByProduct(ctx context.Context, productID int64) ([]*GetCommentsByProductRow, error)
	GetUnSendNotification(ctx context.Context, limit int32) ([]*OutboxNotification, error)
	MaskNotificationAsSend(ctx context.Context, id int64) error
	SaveComment(ctx context.Context, arg *SaveCommentParams) (int64, error)
	SaveNotification(ctx context.Context, arg *SaveNotificationParams) error
}

var _ Querier = (*Queries)(nil)
