version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  comments:
    build: comments
    depends_on:
      - postgres
      - kafka-init-topics
    ports:
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"

  external:
    build: external
    ports:
      - "8093:8093"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: "comments-db"
      POSTGRES_USER: "comments-user-1"
      POSTGRES_PASSWORD: "comments-password-1"
    ports:
      - '5432:5432'

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8092:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.7.1.arm64
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-init-topics:
    container_name: init-topics
    image: confluentinc/cp-kafka:7.7.1.arm64
    depends_on:
      kafka:
        condition: service_healthy
    command: "bash -c 'kafka-topics --create --topic comments.create-comment --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092'"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"